import { borderRadius, colors, fontSize, spacing } from "@/styles/common";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import React, { useState } from "react";
import {
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import Animated, { FadeInDown } from "react-native-reanimated";
import { useSafeAreaInsets } from "react-native-safe-area-context";

// ── Data ──────────────────────────────────────────────────────────────────────

const TERMS_SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing or using Drovery, you agree to be bound by these Terms of Service. If you do not agree to all terms, you may not use our services. We reserve the right to update these terms at any time with reasonable notice.",
  },
  {
    title: "2. Use of Service",
    body: "Drovery provides an on-demand delivery platform connecting senders with couriers. You must be at least 18 years old to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.",
  },
  {
    title: "3. Deliveries & Prohibited Items",
    body: "You agree not to send illegal, hazardous, flammable, explosive, or perishable items that are not declared. Drovery reserves the right to refuse or cancel any delivery suspected of containing prohibited items. You are liable for any damages caused by undisclosed contents.",
  },
  {
    title: "4. Pricing & Payments",
    body: "Delivery fees are calculated based on package size, weight, type, and service level. All prices are displayed before order confirmation. Payment is charged at the time of booking. Refunds are processed within 5–7 business days where applicable.",
  },
  {
    title: "5. Cancellations & Refunds",
    body: "You may cancel a delivery free of charge before a driver is assigned. Cancellations after driver assignment may incur a cancellation fee. Full refunds are issued for service failures attributable to Drovery.",
  },
  {
    title: "6. Limitation of Liability",
    body: "Drovery's liability for any loss or damage is limited to the declared value of the package or the delivery fee paid, whichever is lower. We are not liable for indirect, incidental, or consequential damages arising from use of the service.",
  },
  {
    title: "7. Governing Law",
    body: "These terms are governed by the laws of the Republic of Indonesia. Any disputes shall be resolved through binding arbitration in Jakarta, Indonesia, except where prohibited by local law.",
  },
];

const PRIVACY_SECTIONS = [
  {
    title: "Information We Collect",
    body: "We collect information you provide directly (name, email, phone, address), information generated by your use of the service (order history, location during delivery, device identifiers), and payment information processed securely through our payment partners.",
  },
  {
    title: "How We Use Your Information",
    body: "Your information is used to provide and improve the delivery service, process payments, send transactional notifications, personalise your experience, and comply with legal obligations. We do not sell your personal data to third parties.",
  },
  {
    title: "Location Data",
    body: "We collect your device location when you use the app to enable accurate pickup and delivery. You may disable location access in your device settings, though this will limit certain features. Driver location is shared with you only during an active delivery.",
  },
  {
    title: "Data Sharing",
    body: "We share your data with drivers to complete deliveries, payment processors to handle transactions, and analytics providers to improve our service. All third parties are contractually required to protect your data in accordance with this policy.",
  },
  {
    title: "Data Retention",
    body: "We retain your account data for as long as your account is active. Order history is kept for 3 years for legal and dispute resolution purposes. You may request deletion of your personal data by contacting our support team.",
  },
  {
    title: "Your Rights",
    body: "You have the right to access, correct, or delete your personal data. You may also request data portability or restrict certain processing. To exercise these rights, contact privacy@drovery.com. We will respond within 30 days.",
  },
  {
    title: "Security",
    body: "We use industry-standard encryption (TLS) for data in transit and AES-256 for data at rest. Payment card data is processed by PCI-DSS compliant partners. Despite our measures, no system is completely secure and we cannot guarantee absolute security.",
  },
];

type Tab = "terms" | "privacy";

// ── Component ─────────────────────────────────────────────────────────────────

export function TermsPrivacyScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [activeTab, setActiveTab] = useState<Tab>("terms");
  const [expanded, setExpanded] = useState<number | null>(0);

  const sections = activeTab === "terms" ? TERMS_SECTIONS : PRIVACY_SECTIONS;

  const handleTabChange = (tab: Tab) => {
    setActiveTab(tab);
    setExpanded(0);
  };

  return (
    <View style={[s.root, { paddingTop: insets.top }]}>
      {/* ── Header ── */}
      <LinearGradient
        colors={["#475569", "#334155"]}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
        style={s.header}
      >
        <TouchableOpacity style={s.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={22} color={colors.white} />
        </TouchableOpacity>
        <View style={s.headerText}>
          <Text style={s.headerTitle}>Terms & Privacy</Text>
          <Text style={s.headerSubtitle}>Last updated March 2026</Text>
        </View>
        <View style={s.headerDecor} />
      </LinearGradient>

      {/* ── Tab switcher ── */}
      <View style={s.tabs}>
        <TouchableOpacity
          style={[s.tab, activeTab === "terms" && s.tabActive]}
          onPress={() => handleTabChange("terms")}
        >
          <MaterialIcons
            name="gavel"
            size={16}
            color={activeTab === "terms" ? colors.primary.DEFAULT : colors.text.light}
          />
          <Text style={[s.tabText, activeTab === "terms" && s.tabTextActive]}>
            Terms of Service
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[s.tab, activeTab === "privacy" && s.tabActive]}
          onPress={() => handleTabChange("privacy")}
        >
          <MaterialIcons
            name="shield"
            size={16}
            color={activeTab === "privacy" ? colors.primary.DEFAULT : colors.text.light}
          />
          <Text style={[s.tabText, activeTab === "privacy" && s.tabTextActive]}>
            Privacy Policy
          </Text>
        </TouchableOpacity>
      </View>

      <ScrollView
        contentContainerStyle={[s.content, { paddingBottom: insets.bottom + spacing.xxxl }]}
        showsVerticalScrollIndicator={false}
      >
        <Animated.View key={activeTab} entering={FadeInDown.duration(300)} style={s.sectionsCard}>
          {sections.map((section, i) => (
            <View key={i}>
              <TouchableOpacity
                style={s.sectionRow}
                onPress={() => setExpanded(expanded === i ? null : i)}
                activeOpacity={0.7}
              >
                <Text style={s.sectionTitle}>{section.title}</Text>
                <MaterialIcons
                  name={expanded === i ? "expand-less" : "expand-more"}
                  size={22}
                  color={colors.text.light}
                />
              </TouchableOpacity>
              {expanded === i && (
                <Text style={s.sectionBody}>{section.body}</Text>
              )}
              {i < sections.length - 1 && <View style={s.divider} />}
            </View>
          ))}
        </Animated.View>

        <Text style={s.footer}>
          Questions? Contact us at{" "}
          <Text style={s.footerLink}>legal@drovery.com</Text>
        </Text>
      </ScrollView>
    </View>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const s = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    overflow: "hidden",
    gap: spacing.md,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.xxl,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: fontSize.xl,
    fontWeight: "700",
    color: colors.white,
  },
  headerSubtitle: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.7)",
    marginTop: 2,
  },
  headerDecor: {
    position: "absolute",
    right: -40,
    top: -40,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  // Tabs
  tabs: {
    flexDirection: "row",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.DEFAULT,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingVertical: spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: {
    borderBottomColor: colors.primary.DEFAULT,
  },
  tabText: {
    fontSize: fontSize.sm,
    fontWeight: "500",
    color: colors.text.light,
  },
  tabTextActive: {
    color: colors.primary.DEFAULT,
    fontWeight: "600",
  },
  // Content
  content: {
    padding: spacing.lg,
    gap: spacing.md,
  },
  sectionsCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border.DEFAULT,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    gap: spacing.sm,
  },
  sectionTitle: {
    flex: 1,
    fontSize: fontSize.base,
    fontWeight: "600",
    color: colors.text.primary,
  },
  sectionBody: {
    fontSize: fontSize.sm,
    color: colors.text.secondary,
    lineHeight: 22,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border.light,
    marginHorizontal: 14,
  },
  footer: {
    fontSize: fontSize.sm,
    color: colors.text.placeholder,
    textAlign: "center",
  },
  footerLink: {
    color: colors.primary.DEFAULT,
    fontWeight: "500",
  },
});
